apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-{{.Values.app_NAME}}-volume
  namespace: {{.Values.space_NAME}}
spec:
  capacity:
    storage: 5Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: storage-nfs.sifast.com
    path: /local_nfs/{{.Values.space_NAME}}/{{.Values.app_NAME}}/config
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
