apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-{{.Values.app_NAME}}-volume
  namespace: {{.Values.space_NAME}}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Mi
  volumeName: config-{{.Values.app_NAME}}-volume
