apiVersion: v1
kind: Service
metadata:
  namespace: {{.Values.space_NAME}}
  name: {{.Values.app_NAME}}
  labels:
    app : {{.Values.app_NAME}}
spec:
  selector:
    app: {{.Values.app_NAME}}
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
      nodePort: {{.Values.app_PORT}}
      name: default-port
  type: NodePort
